/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Frame.java
 *
 * Created on Aug 5, 2010, 10:51:20 AM
 */
/**
 *
 * @author oziel
 */
public class Frame extends javax.swing.JFrame {

    /** Creates new form Frame */
    public Frame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        b1.setMaximumSize(new java.awt.Dimension(75, 75));
        b1.setMinimumSize(new java.awt.Dimension(75, 75));
        b1.setPreferredSize(new java.awt.Dimension(75, 75));
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        b2.setMaximumSize(new java.awt.Dimension(75, 75));
        b2.setMinimumSize(new java.awt.Dimension(75, 75));
        b2.setPreferredSize(new java.awt.Dimension(75, 75));
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        b3.setMaximumSize(new java.awt.Dimension(75, 75));
        b3.setMinimumSize(new java.awt.Dimension(75, 75));
        b3.setPreferredSize(new java.awt.Dimension(75, 75));
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        b4.setMaximumSize(new java.awt.Dimension(75, 75));
        b4.setMinimumSize(new java.awt.Dimension(75, 75));
        b4.setPreferredSize(new java.awt.Dimension(75, 75));
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        b5.setMaximumSize(new java.awt.Dimension(75, 75));
        b5.setMinimumSize(new java.awt.Dimension(75, 75));
        b5.setPreferredSize(new java.awt.Dimension(75, 75));
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        b6.setMaximumSize(new java.awt.Dimension(75, 75));
        b6.setMinimumSize(new java.awt.Dimension(75, 75));
        b6.setPreferredSize(new java.awt.Dimension(75, 75));
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        b7.setMaximumSize(new java.awt.Dimension(75, 75));
        b7.setMinimumSize(new java.awt.Dimension(75, 75));
        b7.setPreferredSize(new java.awt.Dimension(75, 75));
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        b8.setMaximumSize(new java.awt.Dimension(75, 75));
        b8.setMinimumSize(new java.awt.Dimension(75, 75));
        b8.setPreferredSize(new java.awt.Dimension(75, 75));
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        b9.setMaximumSize(new java.awt.Dimension(75, 75));
        b9.setMinimumSize(new java.awt.Dimension(75, 75));
        b9.setPreferredSize(new java.awt.Dimension(75, 75));
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Método para atualizar o frame com a jogada da máquina
    private void machinePlayPrint(int pos) {

        if (pos == 1) {
            b1.setText("X");
        } else if (pos == 2) {
            b2.setText("X");
        } else if (pos == 3) {
            b3.setText("X");
        } else if (pos == 4) {
            b4.setText("X");
        } else if (pos == 5) {
            b5.setText("X");
        } else if (pos == 6) {
            b6.setText("X");
        } else if (pos == 7) {
            b7.setText("X");
        } else if (pos == 8) {
            b8.setText("X");
        } else if (pos == 9) {
            b9.setText("X");
        }

    }

    //Métodos para jogadas de usuário no frame
    //b1, b2, ..., b9 são os botões representantes do mapa
    //e seus ActionPerformed() são iguais, mudando a posição a que se referem
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        int lin = 0;
        int col = 0;
        if (ttt.getTurn() == 1) {
            if (ttt.verifyPlay(lin, col)) {
                b1.setText("O");
                ttt.userPlay(lin, col);
                ttt.verifyWin();
                ttt.printMap();
                machinePlayPrint(ttt.machinePlay());
                ttt.verifyWin();
                ttt.printMap();
            }
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        int lin = 0;
        int col = 1;
        if (ttt.getTurn() == 1) {
            if (ttt.verifyPlay(lin, col)) {
                b2.setText("O");
                ttt.userPlay(lin, col);
                ttt.verifyWin();
                ttt.printMap();
                machinePlayPrint(ttt.machinePlay());
                ttt.verifyWin();
                ttt.printMap();
            }
        }
    }//GEN-LAST:event_b2ActionPerformed

    //Limpa o frame e reseta o jogo quando o botão é acionado
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ttt.clearMap();
        b1.setText("");
        b2.setText("");
        b3.setText("");
        b4.setText("");
        b5.setText("");
        b6.setText("");
        b7.setText("");
        b8.setText("");
        b9.setText("");
        ttt.printMap();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        int lin = 0;
        int col = 2;
        if (ttt.getTurn() == 1) {
            if (ttt.verifyPlay(lin, col)) {
                b3.setText("O");
                ttt.userPlay(lin, col);
                ttt.verifyWin();
                ttt.printMap();
                machinePlayPrint(ttt.machinePlay());
                ttt.verifyWin();
                ttt.printMap();
            }
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        int lin = 1;
        int col = 0;
        if (ttt.getTurn() == 1) {
            if (ttt.verifyPlay(lin, col)) {
                b4.setText("O");
                ttt.userPlay(lin, col);
                ttt.verifyWin();
                ttt.printMap();
                machinePlayPrint(ttt.machinePlay());
                ttt.verifyWin();
                ttt.printMap();
            }
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        int lin = 1;
        int col = 1;
        if (ttt.getTurn() == 1) {
            if (ttt.verifyPlay(lin, col)) {
                b5.setText("O");
                ttt.userPlay(lin, col);
                ttt.verifyWin();
                ttt.printMap();
                machinePlayPrint(ttt.machinePlay());
                ttt.verifyWin();
                ttt.printMap();
            }
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        int lin = 1;
        int col = 2;
        if (ttt.getTurn() == 1) {
            if (ttt.verifyPlay(lin, col)) {
                b6.setText("O");
                ttt.userPlay(lin, col);
                ttt.verifyWin();
                ttt.printMap();
                machinePlayPrint(ttt.machinePlay());
                ttt.verifyWin();
                ttt.printMap();
            }
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        int lin = 2;
        int col = 0;
        if (ttt.getTurn() == 1) {
            if (ttt.verifyPlay(lin, col)) {
                b7.setText("O");
                ttt.userPlay(lin, col);
                ttt.verifyWin();
                ttt.printMap();
                machinePlayPrint(ttt.machinePlay());
                ttt.verifyWin();
                ttt.printMap();
            }
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        int lin = 2;
        int col = 1;
        if (ttt.getTurn() == 1) {
            if (ttt.verifyPlay(lin, col)) {
                b8.setText("O");
                ttt.userPlay(lin, col);
                ttt.verifyWin();
                ttt.printMap();
                machinePlayPrint(ttt.machinePlay());
                ttt.verifyWin();
                ttt.printMap();
            }
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        int lin = 2;
        int col = 2;
        if (ttt.getTurn() == 1) {
            if (ttt.verifyPlay(lin, col)) {
                b9.setText("O");
                ttt.userPlay(lin, col);
                ttt.verifyWin();
                ttt.printMap();
                machinePlayPrint(ttt.machinePlay());
                ttt.verifyWin();
                ttt.printMap();
            }
        }
    }//GEN-LAST:event_b9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Frame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    //Declaração do objeto TicTacToe
    TicTacToe ttt = new TicTacToe();
}
